// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_kMgbIaZ_4jDEEyoFP62mwvbqXiZJ3RQ',
    appId: '1:700827935460:web:08e514d4afc1a67e8a42f1',
    messagingSenderId: '700827935460',
    projectId: 'cmsc23-todo-app-jgteknomo',
    authDomain: 'cmsc23-todo-app-jgteknomo.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jgteknomo.appspot.com',
    measurementId: 'G-2TPJQX89L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-OMN38nQDeCp5mIMKaRNnDyD6CTvHuI',
    appId: '1:700827935460:android:48b39d71eeaa6f138a42f1',
    messagingSenderId: '700827935460',
    projectId: 'cmsc23-todo-app-jgteknomo',
    storageBucket: 'cmsc23-todo-app-jgteknomo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_kz8iSLgysdgCfXvE_SeyOlbbDoejyVA',
    appId: '1:700827935460:ios:a0267f34a3079bcb8a42f1',
    messagingSenderId: '700827935460',
    projectId: 'cmsc23-todo-app-jgteknomo',
    storageBucket: 'cmsc23-todo-app-jgteknomo.appspot.com',
    iosClientId: '700827935460-jfoi5piem9cq4obha72oue7s48cql9s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_kz8iSLgysdgCfXvE_SeyOlbbDoejyVA',
    appId: '1:700827935460:ios:a0267f34a3079bcb8a42f1',
    messagingSenderId: '700827935460',
    projectId: 'cmsc23-todo-app-jgteknomo',
    storageBucket: 'cmsc23-todo-app-jgteknomo.appspot.com',
    iosClientId: '700827935460-jfoi5piem9cq4obha72oue7s48cql9s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
